#!/bin/bash

### homebrew (mac) ----------------------------------------
# install homebrew stuff
system_type=$(uname -s)
if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle
  fi

fi

### iterm2 (mac) --------------------------------------------------------
### Configure iTerm2 to use your configuration

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # possibly add something here to ensure iTerm2 is installed using Homebrew
  # cask like in the previous example

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi

fi

### Update the yadm repo origin URL
echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:pat-s/dotfiles.git"

### nvim -------------------------------
nvim_installed=$(which nvim 2>/dev/null || echo FALSE)
if [ "$nvim_installed" != "FALSE" ]; then
  # Install vim Plug
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  # install plugins
  nvim --cmd '' -c 'PlugInstall' -c 'qa!'
else
  echo "nvim not installed, skipping bootstrap actions for nvim"
fi

### fish ------------------------------------
fish_installed=$(which fish 2>/dev/null || echo FALSE)
if [ "$fish_installed" != "FALSE" ]; then
  fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
  fish
  fisher upgrade
else
  echo "fish shell not installed, skipping bootstrap actions"
fi

