k9s:
  cluster: arn:aws:eks:eu-central-1:222488041355:cluster/cynkra-eks-prod
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
  view:
    active: pods
  featureGates:
    nodeShell: true
  portForwardAddress: localhost
